---
- name: Determine shell
  shell: "basename $SHELL"
  register: shell_contents

- name: Install bash-it packages
  shell: . ~/.dotfiles/config/bash/postinstall
  when: shell_contents.stdout.find('bash') != -1

- name: Install vim plugins
  shell: . ~/.dotfiles/config/vim/postinstall

# Run rustup-init for rust

# - name: Install executable binaries to bin
  # with_items:
  #   - https://www.evernote.com/shard/s69/sh/ff1e78f3-a369-4855-b18f-6184ce789c45/f3511927d0fb356ce883835f2eb712e0/res/de33e89a-cdc6-42b5-a476-32e2df1cf4bc/xidel.zip
  # curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.25.0/minikube-darwin-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
  # helm init --upgrade
  # curl -Lo kid https://raw.githubusercontent.com/vyshane/kid/master/kid && chmod +x kid && mv kid /usr/local/bin

#

# - name: Install python globals
#   pip:
#     requirements: ~/.dotfiles/config/python/requirements.txt
#
# - name: Install node globals
#   npm:
#     name: "{{ item }}"
#     global: yes
#   with_items:
#     - prettier
#     - eslint
#     - yarn
#
# TODO: Install golang globals
# Some are covered by vim-go plugin :GoInstallBinaries
# See https://github.com/fatih/vim-go/blob/b50d8f2c89d5955fd923722d8f65a5be3b96b7ca/plugin/go.vim#L32
