[[snippets]]
  description = "Restart video utilities on OS X (for when camera is on but video is black)"
  command = "sudo killall VDCAssistant && sudo killall AppleCameraAssistant"
  output = ""

[[snippets]]
  description = "Finding the pid listening on a specific port on Mac OS"
  command = "lsof -n -i4TCP:8000 | grep LISTEN"
  output = ""
