[[snippets]]
  description = "Restart video utilities on OS X (for when camera is on but video is black)"
  command = "sudo killall VDCAssistant && sudo killall AppleCameraAssistant"
  output = ""

[[snippets]]
  description = "Finding the pid listening on a specific port on Mac OS"
  command = "lsof -n -i4TCP:8000 | grep LISTEN"
  output = ""

[[snippets]]
  description = "Delete all git branches with 'feature' in the name"
  command = "g br -D $(g br | grep feature | tr -d '\\n' | sed  's/\\n//g')"
  output = ""

[[snippets]]
  description = "Select line 736 from file out.log"
  command = "sed '736q;d' out.log"
  output = ""

[[snippets]]
  description = "Replace with capture group"
  command = "sed -r 's/^Reading line (.+)$/\\1/g'"
  output = ""
